# Generated by Django 4.2.29 on 2026-04-06 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=100)),
                ('document_url', models.URLField()),
                ('issuing_country', models.CharField(default='Rwanda', max_length=100)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='submitted', max_length=20)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_document', to='accounts.tenantprofile')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
