# Generated by Django 4.2.29 on 2026-04-06 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordDocumentVerificationAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('provider_code', models.CharField(default='national-registry', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_document_verification_access', to=settings.AUTH_USER_MODEL)),
                ('landlord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_verification_access', to='accounts.landlordprofile')),
            ],
            options={
                'ordering': ('landlord__display_name',),
            },
        ),
    ]
