# Generated by manual schema sync for Housify map hierarchy.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("center_latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("center_longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("center_latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("center_longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectors",
                        to="locations.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sector",
                "verbose_name_plural": "Sectors",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("center_latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("center_longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="locations.sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cell",
                "verbose_name_plural": "Cells",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("center_latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("center_longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                (
                    "cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villages",
                        to="locations.cell",
                    ),
                ),
            ],
            options={
                "verbose_name": "Village",
                "verbose_name_plural": "Villages",
                "ordering": ("name",),
            },
        ),
        migrations.AddConstraint(
            model_name="sector",
            constraint=models.UniqueConstraint(fields=("district", "name"), name="unique_sector_name_per_district"),
        ),
        migrations.AddConstraint(
            model_name="cell",
            constraint=models.UniqueConstraint(fields=("sector", "name"), name="unique_cell_name_per_sector"),
        ),
        migrations.AddConstraint(
            model_name="village",
            constraint=models.UniqueConstraint(fields=("cell", "name"), name="unique_village_name_per_cell"),
        ),
    ]
