# Generated by manual schema sync for Housify map hierarchy.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="sector",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="cell",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="village",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
