# Generated by Django 6.0.3 on 2026-04-05 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('monthly_rent_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('security_deposit_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('billing_cycle_snapshot', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tenancies', to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='accounts.landlordprofile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='accounts.tenantprofile')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active'])), fields=('property',), name='unique_open_tenancy_per_property')],
            },
        ),
    ]
